# -*- coding: utf-8 -*-
"""EX 01 Three-Layer Neural Network From Scratch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vatSLU5FsJAGLp2QDBLnSi49rMaMuaOl
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras import layers, models
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.astype('float32') / 255
x_test = x_test.astype('float32') / 255

x_train = x_train.reshape((x_train.shape[0],28*28))

model = models.Sequential()

model.add(layers.Dense(128,
activation='relu',
input_shape=(784,)))

activation='relu'

model.add(layers.Dropout(0.2))

model.add(layers.Dense(10,
activation='softmax'))

model.compile(
optimizer='adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy']
)

model.fit(
x_train,
y_train,
epochs=5,
batch_size=32,
validation_split=0.2
)

x_test = x_test.reshape((x_test.shape[0], 28 * 28))

test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {test_acc:.4f}")

predictions = model.predict(x_test)

for i in range(5):
    plt.imshow(x_test[i].reshape(28,28), cmap='gray')
    plt.title(
        f"Predicted:{np.argmax(predictions[i])}, Actual:{y_test[i]}"
    )
    plt.axis('off')
    plt.show()

